name: flutter_test_app
version: 1.0.0+1
publish_to: none
description: A new Flutter application.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  google_fonts: ^2.1.1
  responsive_grid: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/images/category/
    - assets/images/product/
    - assets/images/other/

